# Generated by Django 5.0 on 2024-03-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_rename_texts_contact_desc_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='message',
        ),
    ]
