# Generated by Django 5.0 on 2024-03-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
