# Generated by Django 5.0 on 2024-03-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.country')),
            ],
        ),
    ]
