# Generated by Django 5.0 on 2024-03-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_touristlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGroupBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('total_participants', models.IntegerField()),
            ],
            options={
                'db_table': 'active_group_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewGroupBookingTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'new_group_booking_trigger',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='touristlocation',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('total_participants', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.touristlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('group_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.groupbooking')),
            ],
        ),
    ]
