# Generated by Django 5.0 on 2024-03-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_activegroupbookings_newgroupbookingtrigger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('names', models.TextField()),
                ('num_people', models.PositiveIntegerField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
