# Generated by Django 5.0 on 2024-03-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_rename_user_itinerary_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='users',
        ),
    ]
