# Generated by Django 5.0 on 2024-03-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_rename_users_itinerary_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel.groupbooking')),
            ],
        ),
    ]
