# Generated by Django 5.0 on 2024-03-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_groupbooking_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='group_booking',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
