# Generated by Django 5.1.3 on 2024-11-13 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_remove_bookinghistory_group_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingHistory',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RemoveField(
            model_name='touristlocation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='groupbooking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActiveGroupBookings',
        ),
        migrations.DeleteModel(
            name='NewGroupBookingTrigger',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.post'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='GroupBooking',
        ),
        migrations.DeleteModel(
            name='TouristLocation',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
