# Generated by Django 5.1.3 on 2024-11-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
